---
on:
  push:
    branches:
      - master

jobs:
  pushImage:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Build image
        run: docker build -t bfg .

      - name: Login to Docker Hub
        run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Tag Docker image
        run: docker tag bfg koenrh/bfg

      - name: Push image to Docker Hub
        run: docker push koenrh/bfg
